# Unidad 2 Tarea 2

# Ejercicios Método de la potencia

+ ### Julian Emiliano Ortiz Rivero
+ ### Angel Mariel Osalde Salazar
+ ### Miguel Omar Solis Rodriguez 



# Introducción
<p style="text-align: justify;">
En esta unidad, hemos estudiado los conceptos de eigenvalores y eigenvectores de una matriz, así como sus propiedades inherentes. Para finalizar la unidad, nos embarcamos en una serie de ejercicios que nos permiten aplicar y profundizar en este conocimiento adquirido.
</p>
<p style="text-align: justify;">
No solo nos limitamos a resolver problemas; también nos sumergimos en demostraciones que, al desentrañar su lógica matemática, nos brindan una comprensión más profunda de las aplicaciones de estos conceptos en diversos contextos.
</p>
<p style="text-align: justify;">
Finalmente, pero no menos importante, resolverenmos ejercicios de cómputo. Reconocemos que, si bien el dominio del conocimiento matemático es fundamental en nuestro campo, la capacidad de llevar estos principios a la práctica computacional es esencial. De esta manera, podemos aprovechar plenamente el poder de cálculo disponible y traducir nuestras ideas en aplicaciones de cómputo.
</p>

# __Índice__

<ol>
    <li><a href="#int">Introducción</a></li>
    <li><a href="#Indice">Índice</a></li>
    <li><a href="#voyva">Ejercicios y demostraciones</a>
        <ol type="i">
            <li><a href="#">Ejercicio 4.1</a></li>
            <ol type="a">
            <li><a href="#a">Inciso a</a></li>
            <li><a href="#b">Inciso b</a></li>
            </ol>
            <li><a href="#">Ejercicio 4.2</a></li>
            <ol type="a">
            <li><a href="#a">Inciso a</a></li>
            <li><a href="#b">Inciso b</a></li>
            </ol>
            <li><a href="#">Ejercicio 4.3</a></li>
            <ol type="a">
            <li><a href="#a">Inciso a</a></li>
            <li><a href="#b">Inciso b</a></li>
            <li><a href="#a">Inciso c</a></li>
            <li><a href="#b">Inciso d</a></li>
            <li><a href="#a">Inciso e</a></li>
            <li><a href="#b">Inciso f</a></li>
            <li><a href="#a">Inciso g</a></li>
            <li><a href="#b">Inciso h</a></li>
            <li><a href="#a">Inciso i</a></li>
            <li><a href="#b">Inciso j</a></li>
            </ol>
            <li><a href="#">Ejercicio 4.5</a></li>
            <ol type="a">
            <li><a href="#a">Inciso a</a></li>
            <li><a href="#b">Inciso b</a></li>
            </ol>
            <li><a href="#">Ejercicio 4.12</a></li>
            <li><a href="#">Ejercicio 4.14</a></li>
            <li><a href="#">Ejercicio 4.16</a></li>
        </ol>
    </li>
    <li><a href="#4">Ejercicios de cómputo</a></li>
    <ol type="i">
            <li><a href="#">Ejercicio 4.1</a></li>
                <ol type="a">
                    <li><a href="#a">Inciso a</a></li>
                </ol>
            <li><a href="#">Ejercicio 4.2</a></li>
                <ol type="a">
                    <li><a href="#a">Inciso a</a></li>
                    <li><a href="#a">Inciso c</a></li>
                </ol>
            <li><a href="#">Ejercicio 4.4</a></li>
            <li><a href="#">Ejercicio 4.6</a></li>
            <li><a href="#">Ejercicio 4.14</a></li>
                <ol type="a">
                    <li><a href="#a">Inciso a</a></li>
                    <li><a href="#a">Inciso b</a></li>
                </ol>
    </ol>
    <li><a href="#4">Conclusíon</a></li>
</ol>


__4.1 (a)	Demuestre que 5 es un eigenvalor de la matriz__<a id="1"></a>
$$
\begin{align}
  A = \begin{bmatrix}
  6 & 3 & 3 & 1 \\
  0 & 7 & 4 & 5 \\
  0 & 0 & 5 & 4 \\
  0 & 0 & 0 & 8 \\
\end{bmatrix}
\end{align}
$$


Para saber si 5 es un eigenvalor de la matriz, este debe ser una raiz del polinomio característico con $ p(5) = 0 $ donde $p(\lambda) $ es el polinomio caracteristico.

Utilizando la definición del polinomio característico $ p(\lambda) = det(A - \lambda I) $
Se calcula el polinomio carcacterístico siendo : 

$$
\begin{align*}
    p(\lambda) = (\lambda -  6)( \lambda - 7) ( \lambda - 5 )( \lambda - 8)\\
\end{align*}
$$

Ahora $p(5) = (\lambda -  6)( \lambda - 7) ( 0 )( \lambda - 8) = 0$, Así $\lambda = 5$ es una raiz del polinomio característico. Entonces $ \lambda = 5 $ es un valor propio de la matriz A.


In [1]:
import numpy as np
from scipy.linalg import expm
import sympy as sp
import pandas as pd


In [2]:
# Definición de la matriz A
A = sp.Matrix([[6, 3, 3, 1], [0, 7, 4, 5], [0, 0, 5, 4], [0, 0, 0, 8]])

# (a) Prove that 5 is an eigenvalue of the matrix A
eigenvalores = A.eigenvals()
if 5 in eigenvalores:
    print("5 es un eigenvalor de la matriz A.")
else:
    print("5 no es un eigenvalor de la matriz A.")

5 es un eigenvalor de la matriz A.



* **(b)	Calcular un vector propio de A correspondiente al valor propio 5.**

Para $ \lambda = 5$ resolvemos $(A - \lambda I) = 0 $, o bien : 
$$
\begin{align*}
    A = \begin{pmatrix}
      1 & 3 & 3 & 1 \\
      0 & 2 & 4 & 5 \\
      0 & 0 & 0 & 4 \\
      0 & 0 & 0 & 3 \\
    \end{pmatrix}
    \begin{pmatrix}
      x_1 \\
       x_2\\
       x_3 \\
       x_4
    \end{pmatrix}
    =
    \begin{pmatrix}
      0 \\
       0\\
       0 \\
       0
    \end{pmatrix}
\end{align*}
$$ 

De esta manera $ x_4 = 0, 2x_2 + 4x_3 = 0, x_1 - 3 x_3 = 0 $ y un vector propio es :
$$
\begin{align*}
  x = \begin{pmatrix}
      3 \\
       -2\\
       1 \\
       0
    \end{pmatrix}
\end{align*}
$$
Entonces, cualquier múltiplo no nulo de $  x = \begin{pmatrix}  3 \\ -2\\ 1 \\  0 \end{pmatrix} $
es un vector propio de A correspondiente el valor propio $\lambda = 5 $

In [3]:
# (b) Exhibit an eigenvector of A corresponding to the eigenvalue 5
eigenvectores = A.eigenvects()
for eigenval, multiplicity, eigenvect_list in eigenvectores:
    if eigenval == 5:
        eigenvect = eigenvect_list[0]  # Selecting one eigenvector
        print("El eigenvector de A corresponde al eigenvalor 5: ")
        print(eigenvect)
        break


El eigenvector de A corresponde al eigenvalor 5: 
Matrix([[3], [-2], [1], [0]])


__4.2  ¿Cuáles son los valores propios y los correspondientes vectores propios de la siguiente matriz?__
$$
\begin{align}
 A =  \begin{bmatrix}
  1 & 2 & -4 \\
  0 & 2 & 1 \\
  0 & 0 & 3
\end{bmatrix}
\end{align}
$$

Se puede observar que la matriz A es triangular superior, entonces por propiedades de la matriz triangular, se tiene que sus valores propios son sus entradas diagonales, es decir, $ \lambda_1 = 1, \quad \lambda_2 = 2, \quad \lambda_3 = 3 $

* Para $\lambda_1 = 1$ tenemos 
$$
\begin{align*}
  (A - I)x 
  =
  \begin{bmatrix}
    0 & 2 & -4 \\
    0 & 1 & 1 \\
    0 & 0 & 2
  \end{bmatrix} 
  \begin{bmatrix}
    x_1 \\
     x_2 \\
     x_3 
  \end{bmatrix} 
  =
  \begin{bmatrix}
    0 \\
     0 \\
     0 
  \end{bmatrix} 
\end{align*}
$$

De esta manera $x_3 = 0,\quad x_2 = -x_3,\quad x_2 = 2x_3$ y un vector propio es : 
$$
\begin{align*}
  x = \begin{bmatrix}
    1 \\
     0 \\
     0 
  \end{bmatrix} 
\end{align*}
$$

* Para $ \lambda = 2 $ tenemos 
$$
\begin{align*}
  (A - 2I)x 
  =
  \begin{bmatrix}
    -1 & 2 & -4 \\
    0 & 0 & 1 \\
    0 & 0 & 1
  \end{bmatrix} 
  \begin{bmatrix}
    x_1 \\
     x_2 \\
     x_3 
  \end{bmatrix} 
  =
  \begin{bmatrix}
    0 \\
     0 \\
     0 
  \end{bmatrix} 
\end{align*}
$$
De esta manera $x_3 = 0,\quad x_1 = 2x_2 $ y un vector propio es : 
$$
\begin{align*}
  x = \begin{bmatrix}
     2\\
     1 \\
     0 
  \end{bmatrix} 
\end{align*}
$$

* Para $ \lambda = 3 $ tenemos 
$$
\begin{align*}
  (A - 3I)x 
  =
  \begin{bmatrix}
    -2 & 2 & -4 \\
    0 & -1 & 1 \\
    0 & 0 & 0
  \end{bmatrix} 
  \begin{bmatrix}
    x_1 \\
     x_2 \\
     x_3 
  \end{bmatrix} 
  =
  \begin{bmatrix}
    0 \\
     0 \\
     0 
  \end{bmatrix} 
\end{align*}
$$
De esta manera $x_2 = x_3,\quad x_1 = -x_3 $ y un vector propio es : 
$$
\begin{align*}
  x = \begin{bmatrix}
     -1\\
     1 \\
     1 
  \end{bmatrix} 
\end{align*}
$$

In [4]:
# definición de variables
A = sp.Matrix([[1, 2, -4], [0, 2, 1], [0, 0, 3]])
eigenvalores = A.eigenvals()
eigenvectores = A.eigenvects()

# Imprime los eigenvalores
for i, eigenval in enumerate(eigenvalores):
    print(f"Eigenvalue λ_{i+1}: {eigenval}")
print("\n")
# Imprime los eigenvectores
for i, (eigenval, multiplicity, eigenvect) in enumerate(eigenvectores):
    print(f"Eigenvector de λ_{i+1}:")
    for vector in eigenvect:
        print(vector)



Eigenvalue λ_1: 3
Eigenvalue λ_2: 2
Eigenvalue λ_3: 1


Eigenvector de λ_1:
Matrix([[1], [0], [0]])
Eigenvector de λ_2:
Matrix([[2], [1], [0]])
Eigenvector de λ_3:
Matrix([[-1], [1], [1]])


__4.3 Sea :__ 
$$
\begin{align}
    A = \begin{bmatrix}
 1  & 4 \\
 1  & 1 \\
\end{bmatrix}
\end{align}
$$


In [28]:
# from numpy.linalg import inv

# Definición de la matriz A
A = sp.Matrix([[1, 4], [1, 1]])

# Calcula los eigenvalores y sus multiplicidades
eigenvalores = A.eigenvals()
eigenvectores = A.eigenvects()

# Construye el polinomio característico
λ = sp.symbols('λ')
polinomio_caracteristico = A.charpoly(λ).as_expr()



Las respuestas a las siguientes preguntas deben ser numéricas y específicas a esta matriz en particular, no sólo a las definiciones generales.

* **(a)¿Cuál es el polinomio característico de A?**


Sea $ A = \begin{bmatrix} 1 & 4 \\ 1 & 1 \\ \end{bmatrix} $. 
Entonces 
$$
\begin{align*}
    P(\lambda) &= det(A-\lambda I) 
    &&=
    \left |
    \begin{bmatrix}
      1 - \lambda & 4 \\
     1  & 1 - \lambda \\
    \end{bmatrix}
    \right | \\
    &= (1 - \lambda)^2 - 4 &&= \lambda^2 - 2 \lambda - 3 \\
\end{align*}
$$

Por lo tanto el polinomio caracteristico es : $ \lambda^2 - 2 \lambda - 3 $

In [29]:
polinomio_caracteristico


* (b) ¿Cuáles son las raíces del polinomio característico asociado a la matriz A?


Considere el polinomio característico $ P(\lambda) = \lambda ^2 - 2\lambda -3$ asosiado a la matriz A. Entonces podemos factorizarlo como :
$$
\begin{align*}
    &P(\lambda) = \lambda ^2 - 2\lambda -3 \\
    &P(\lambda) = (\lambda+1)(\lambda -3)\\ \\
\end{align*}
$$
Las raíces de $P(\lambda) $ son aquellos valores tal que $P(\lambda) = 0 $, es decir, $ (\lambda+1)(\lambda -3) = 0 $. Entonces $\lambda_1 = -1 \quad y \quad \lambda_2 = 3. $

In [7]:
roots = sp.solve(polinomio_caracteristico, λ)
for i, root in enumerate(roots):
    print(f"Root {i+1}: {root}")

Root 1: -1
Root 2: 3


* (c)  **¿Cuáles son los valores propios de la matriz A?**

Como $\lambda_1 = -1 \quad y \quad \lambda_2 = 3. $ satisfacen $ P(\lambda) = det(A-\lambda I) = \lambda ^2 - 2\lambda -3 $ entonces $ \lambda_1 , \lambda_2 $ son valores propios de la matriz A.

In [8]:
for i, eigenval in enumerate(eigenvalores):
    print(f"Eigenvalue λ_{i+1}: {eigenval}")


Eigenvalue λ_1: 3
Eigenvalue λ_2: -1



* **(d) ¿Cuáles son los correspondientes vectores propios de la matriz A?**


 + Para $ \lambda_1 = -1 $ tenemos
$$
\begin{align*}
  (A + I)x 
  =
  \begin{bmatrix}
    2 & 4 \\
    1 & 2 
  \end{bmatrix} 
  \begin{bmatrix}
    x_1 \\
     x_2  
  \end{bmatrix} 
  =
  \begin{bmatrix}
    0 \\
     0  
  \end{bmatrix} 
\end{align*}
$$
De esta manera $x_1 = -2x_2,\quad 0 \quad x_2 = -1/2x_1 $ y un vector propio es : 
$$
\begin{align*}
  x = \begin{bmatrix}
     1\\
     -1/2 
  \end{bmatrix} 
\end{align*}
$$

 + Para $ \lambda_2 = 3 $ tenemos
$$
\begin{align*}
  (A -3I)x 
  =
  \begin{bmatrix}
    -2 & 4 \\
    1 & -2 
  \end{bmatrix} 
  \begin{bmatrix}
    x_1 \\
     x_2  
  \end{bmatrix} 
  =
  \begin{bmatrix}
    0 \\
     0  
  \end{bmatrix} 
\end{align*}
$$
De esta manera $x_1 = 2x_2,\quad 0 \quad x_2 = 1/2x_1 $ y un vector propio es : 
$$
\begin{align*}
  x = \begin{bmatrix}
     1\\
     1/2 
  \end{bmatrix} 
\end{align*}
$$

In [9]:

for i, (eigenval, multiplicity, eigenvect) in enumerate(eigenvectores):
    print(f"Eigenvector de λ_{i+1}:")
    for vector in eigenvect:
        print(vector)

Eigenvector de λ_1:
Matrix([[-2], [1]])
Eigenvector de λ_2:
Matrix([[2], [1]])


* **(e) Realiza una iteración del método de la potencia sobre A, utilizando $ X_0 =  \begin{bmatrix} 1 \\ 1 \end{bmatrix} $ como vector inicial.**

Definimos librerias y métodos a usar.

In [10]:
import numpy as np
from sympy import * 
init_printing(use_unicode=True) 
import pandas as pd
from numpy.linalg import inv

np.set_printoptions(suppress=True)

In [11]:
def rayleigh_Quotient(matrix, vector):
    numerador = np.dot(vector.T, np.dot(matrix, vector))
    denominador = np.dot(vector.T, vector)
    rq = numerador / denominador
    return rq

def normalize(x):
    fac = abs(x).max()
    x_n = x / x.max()
    return fac, x_n

def powerMethodN(a,x,iter):
    result = pd.DataFrame(columns=['x_k', 'norm(y)_infinity'])
    result.loc[0] = [x,'---']
    for i in range(iter-1):
        x = np.dot(a,x)
        lambda_1,x = normalize(x)
        result.loc[i+1]= [x,lambda_1]
    return result
    
def powerMethods(a,x,iter):
    for i in range(iter-1):
        x = np.dot(a,x)
        result = x 
        print("metodo de las potencias")
        print(i+1,x)
    

def PowerMethodsRQ(a, x, iter):
    result = pd.DataFrame(columns=['x_k', 'norm(y)_infinity', 'RQ'])
    # x debe ser un vector no nulo en Rn
    # a se asume que la matriz A tiene un eigenvalor dominante con los correspondientes eigenvectores dominantes
    
    # Calcular el cociente de Rayleigh inicial
    rq = rayleigh_Quotient(a, x)
    result.loc[0] = [x, '---', rq]
    
    for i in range(iter-1):
        # Aplicar el método de la potencia
        x = np.dot(a, x)
        # Normalizar el vector resultante y calcular el cociente de Rayleigh
        lambda_1, x = normalize(x)
        rq = rayleigh_Quotient(a, x) 
        # Registrar los resultados en el dataframe
        result.loc[i+1] = [x, lambda_1, rq]
        
    return result

def RQI(a,x,itera):
    result = pd.DataFrame(columns=['x_k','norm(y)_infinity', 'RQ'])
    rq = np.dot(x.T, np.dot(a, x)) / np.dot(x.T, x)
    x=np.dot(a-rq*np.eye(2),x)
    result.loc[0]=[x,'---',rq]
    for i in range(itera-1):
        x = np.dot(a, x)
        # normalizamos
        x /= np.linalg.norm(x, np.inf)
        rq = np.dot(x.T, np.dot(a, x)) / np.dot(x.T, x)
        a = a-rq*np.eye(2)
        result.loc[i+1]=[x, np.linalg.norm(np.dot(a, x), np.inf), rq]
    return result

def powerMethod_inv(a,x,itera):
    """ metodo de la potencia inversa"""
    
    result = pd.DataFrame(columns=['x_k','norm(y)_infinity'])
    a_inv = inv(a)
    result.loc[0] = [x,'---']
    for i in range(itera-1):
        x = np.dot(a_inv,x)
        lamba_1, x = normalize(x)
        result.loc[i+1] = [x, lamba_1]
    return result


def qr_iteration(A,num_iter=3):
    n = A.shape[0]
    Q = np.eye(n)
    
    for i in range(num_iter):
        Q,R = np.linalg.qr(A @ Q)
        A = R @ Q 
        print ( f"iteracion {i+1}:\n {A}")
    eigenvalues = np.diag(A)
    return eigenvalues


Resolvemos para (e)

In [12]:
# iteramos una vez en el metodo de la potencia
x = np.array([1,1]) 
a = np.array([[1,4],
              [1,1]])

itera = 2

powerMethods(a,x,itera)
powerMethodN(a,x,itera)


metodo de las potencias
1 [5 2]


x_k norm(y)_infinity
0      [1, 1]              ---
1  [1.0, 0.4]                5


* **(f)  ¿A qué vector propio de A convergerá finalmente el método de la potencia?**


(f)  Elejimos un vector inicial $x_0$:
$$
\begin{align}
    x_0 = \begin{bmatrix}
  1\\
  1
\end{bmatrix}
\end{align}
$$
y aplicamos el metodo de iteracion de potencia con el cociente de rayleigh para determinar la convergencia.

In [13]:
# Define la matriz A
A = np.array([[1, 4], [1, 1]])

# Define el vector inicial x_0
x_0 = np.array([1, 1])

resultados = PowerMethodsRQ(A,x_0,10)
pd.DataFrame(resultados.iloc[9]).transpose()


x_k norm(y)_infinity        RQ
9  [1.0, 0.4999830651989839]         3.000203  2.999959

Por lo tanto el eigenvector hacia la cual converge la irateración de potencia es aproximadamente : 
$$
\begin{align}
    v \approx \begin{bmatrix}
      1.0\\
      0.5
    \end{bmatrix}
\end{align}
$$


* **(g)  ¿Qué estimación de valor propio viene dada por el cociente de Rayleigh, utilizando el vector $ x = \begin{bmatrix} 1 & 1 \\ \end{bmatrix}^T $ ?**


In [14]:
x = np.array([1,1]) 
a = np.array([[1,4],[1,1]]) 

rayleigh_Quotient(a,x)


* **(h) ¿A qué vector propio de A convergería finalmente la iteración inversa?**


In [15]:
x = np.array([1, 1])
a = np.array([[1,4],[1,1]]) 
itera=10 
powerMethod_inv(a,x,itera)

x_k norm(y)_infinity
0                       [1, 1]              ---
1                   [1.0, 0.0]              1.0
2   [-0.9999999999999998, 1.0]         0.333333
3  [1.0, -0.39999999999999997]         1.666667
4    [-1.857142857142857, 1.0]         0.866667
5  [1.0, -0.48780487804878053]         1.952381
6   [-1.9836065573770492, 1.0]          0.98374
7  [1.0, -0.49863013698630143]         1.994536
8   [-1.9981718464351004, 1.0]         0.998174
9   [1.0, -0.4998476074367571]         1.999391

Convergerá a un múltiplo de vector propio correspondiente al valor propio de menor magnitud : 
$$
\begin{align*}
  x =   \begin{bmatrix}
       1\\
       -0.5
    \end{bmatrix}
\end{align*}
$$


* **$(i)$ ¿Qué valor propio de A se obtendría si iteración inversa con desplazamiento σ = 2?**


In [16]:
x = np.array([1, 1])
A = np.array([[1,4],[1,1]]) 
shift = 2
max_iter = 100
tol = 1e-6
for i in range(max_iter):
    x = np.linalg.solve(A - shift * np.eye(A.shape[0]),x)
    x = x/np.linalg.norm(x)
    eigenvalue = np.dot(x.T, np.dot(A, x)) / np.dot(x.T, x)
    if np.abs(np.dot(A,x)-shift * x).max() < tol: break

print("Eigenvalue:",eigenvalue)

Eigenvalue: 3.0



* **(j) Si se aplicara la iteración QR a la matriz A, a qué forma convergería: ¿diagonal o triangular? ¿Por qué?**



In [17]:

A = np.array([[1,4],[1,1]]) 
eigenvalores = qr_iteration(A)
print("Eigenvalores :",eigenvalores)

iteracion 1:
 [[ 3.5 -1.5]
 [ 1.5 -1.5]]
iteracion 2:
 [[-1.41421356  3.53553391]
 [-0.         -2.12132034]]
iteracion 3:
 [[ 1.41421356 -3.53553391]
 [-0.         -2.12132034]]
Eigenvalores : [ 1.41421356 -2.12132034]


Por lo tanto convergera a una matriz triangular, ya que A no es simétrica

__4.5. Supongamos que todas las sumas de fila de una matriz n × n matriz A tienen el mismo valor, digamos, α.__


* (a) **Demuestre que α es un valor propio de A.**

Primero expresamos comodamente lo que nos dicen : 

$\text{"Supongamos que todas las sumas de filas de una matriz A de n x n tienen el mismo valor, digamos α"}$

Esto puede verse como : 

$$
\begin{align}
    \left[ \begin{array}{ccccc|c}
    a_1  & a_2 & \cdots & a_{n-1} & a_n & \alpha\\
    b_1  & b_2 & \cdots & b_{n-1} & b_n & \alpha\\
    \vdots  & \vdots & \vdots & \vdots & \vdots & \vdots\\
    n_1 & n_2 & \cdots  &n_{n-1} & n_n & \alpha \\
    \end{array} \right]
\end{align}
$$

siendo asi 
$$
\begin{align}
\begin{bmatrix}
    a_1  & a_2 & \cdots & a_{n-1} & a_n \\
    b_1  & b_2 & \cdots & b_{n-1} & b_n \\
    \vdots  & \vdots & \vdots & \vdots & \vdots \\
    n_1 & n_2 & \cdots  &n_{n-1} & n_n \\
\end{bmatrix}
=
\begin{bmatrix}
    \alpha\\
    \alpha\\
    \alpha\\
    \alpha \\
    \end{bmatrix}
\end{align}
$$
Factorizando $\alpha $ tenemos : 
$$
\begin{align}
\begin{bmatrix}
    a_1  & a_2 & \cdots & a_{n-1} & a_n \\
    b_1  & b_2 & \cdots & b_{n-1} & b_n \\
    \vdots  & \vdots & \vdots & \vdots  \\
    n_1 & n_2 & \cdots  &n_{n-1} & n_n \\
\end{bmatrix}
\begin{bmatrix}
    1\\
    1\\
    \vdots\\
    1 \\
    \end{bmatrix}
= \alpha
\begin{bmatrix}
    1\\
    1\\
    \vdots\\
    1 \\
    \end{bmatrix}
\end{align}
$$


Con esto establecido, sabemos que para obtener los eigenvalores se debe hacer : $ Ax = \lambda x $ 

en este caso buscamos $ \lambda = \alpha $

Entonces, de la igualdad anterior determinamos que $\alpha$ es un eigenvalor de A tal que cumple con : $ Ax = \alpha x $ donde x es su eigenvector

$$
\begin{align}
Ax = \alpha x \rightarrow \begin{bmatrix}
    a_1  & a_2 & \cdots & a_{n-1} & a_n \\
    b_1  & b_2 & \cdots & b_{n-1} & b_n \\
    \vdots  & \vdots & \vdots & \vdots  \\
    n_1 & n_2 & \cdots  &n_{n-1} & n_n \\
\end{bmatrix}
\begin{bmatrix}
    1\\
    1\\
    \vdots\\
    1 \\
    \end{bmatrix}
= \alpha
\begin{bmatrix}
    1\\
    1\\
    \vdots\\
    1 \\
    \end{bmatrix}
\end{align}
$$

`por lo que para este caso,` $\alpha $ `es un eigen valor de una matriz nxn`




* (b)  **¿Cuál es el vector propio correspondiente?**

Por lo anterior se ha demostrado que $\alpha $ es un eigenvalor de A y 
` x es un eigen vector de la matriz A `
$$
\begin{align}
    x = \begin{bmatrix}
      1\\
      1\\
      \vdots \\
      1
    \end{bmatrix}
\end{align}
$$

__4.12.  Demostrar que los valores propios de una matriz positiva definida  son todos positivos.__


Usamos la definicion de la matriz definida positiva  

Una matriz M es definida positiva solo si existe un vector X tal que su producto escalar es positivo : 
$$
\begin{align}
    X^T M X > 0 \quad \text{ para todo } x \in
 R^n \
\end{align}
$$


Con la definicion anterior, la acompletamos usando las propiedades de los eigenvalores que ya conocemos : 
$$
\begin{align}
    Ax = \lambda x 
\end{align}
$$
Ahora, para saber que la matriz A es definida positiva y que eigenvector correspondiente es $v$ con su eigenvalor $ \lambda$, le aplicamos la definicion de la matriz definida positiva : 

$$
\begin{align}
    X^T A X = \lambda X^T X
\end{align}
$$
Como vemos, el producto escalar de $ X^T X $  es un vector escalar y este a su vez representa la norma al cuadrado de X, podemos decir que $ X^T X > 0 $ para cualquier vector no nulo.


Es decir, $ \lambda$ debera ser positiva, ya que $ X^T A X $ es positivo y $\lambda X^T X $ igual es positivo 

```Por lo tanto, todos los eigenvalores de una matriz definida positiva son positivos``` 

__4.14.  Demostrar que para cualquier norma matricial inducida por una norma vectorial, ρ(A)≤||A||__


Sea $ \lambda$ un valor propio de A con su correspondiente vector propo de x. Entonces $ Ax = \lambda x $ o equivalentemente $ \lambda x = Ax $, esto implica que  $ |\lambda | \| x \| \leq \| A \| \| x \| $ entonces $| \lambda| \leq \| A \| $ esta desigaldad se cumple para cualquier valor propio de módulo mayor de modo que $\rho(A) \leq \|A\| $

__4.16. Supongamos que A es una matriz n x n no singular.__

* (a) **¿Cuál es la relación entre los valores propios de A y  los de $A^{-1}$. Demuestre su respuesta.**


Suponga que $ \lambda $ es un valor propio de una matriz no singular $ A_{nxn}$ entonces existe un vector $v \in \mathbb{R}^n  $ tal que $ Av = \lambda v $

como A es invertible entonces existe $ A^{-1} $ 
$$
\begin{align*}
    A^{-1}Av = A^{-1}\lambda v = \lambda A^{-1} v
\end{align*}
$$
o equivalentemente :
$$
\begin{align*}
    \lambda A^{-1} v = I_{nxn}v = v
\end{align*}
$$
de la igualdad anterior y la matriz A invertible, $\lambda \ne  0$
$$
\begin{align*}
    A^{-1}v = \frac{1}{\lambda} v
\end{align*}
$$
Por tanto $\frac{1}{\lambda} $ es un valor propio de la matriz A con su corresponiente vector v

Los valores propios de $A^{-1}$ son los recíprocros de los valores propios de A


* (b) **¿Cuál es la relación entre los vectores propios de A y  los de $A^{-1}$. Demuestre su respuesta.**

La relacion entre los vectores propios de A y los de $A^{-1}$ es que si v es un vector propio de A correspondiente al valor propio $ \lambda $, entonces v también es un vector propio de A^{-1} correspondiente al valor propio $ \frac{1}{\lambda} $.Esto proporcionado por el análisis anterio.

# Problemas de cómputo


__4.1 ( a )  Calcular los valores y vectores propios de la matriz__

$$
\begin{align}
    A = \begin{bmatrix}
     1  & 1000\\
     0.001 & 1
    \end{bmatrix}
\end{align}
$$



In [18]:

A = np.array([[1, 1000],
              [0.001, 1]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[2. 0.]

Eigenvectors:
[[ 0.9999995 -0.9999995]
 [ 0.001      0.001    ]]


__4.2 ( a )  Aplicar el método de la potencia para hallar el valor propio dominante y el correspondiente eigenvector de la matriz__

$$
\begin{align}
    A = \begin{bmatrix}
      2 & 3 & 2 \\
      10 & 3 & 4 \\
      3 & 6 & 1
    \end{bmatrix}
\end{align}
$$

As starting vector, take 
$$
\begin{align}
 X_0 =  \begin{bmatrix}
   0  & 0 & 1 
  \end{bmatrix}^T
\end{align}
$$


In [19]:

A = np.array([[2, 3, 2],
              [10, 3, 4],
              [3, 6, 1]])
x0 = np.array([0, 0, 1]).reshape(-1, 1)
max_iterations = 1000
tolerance = 1e-6
x = x0
for i in range(max_iterations):
    Ax = np.dot(A, x)
    norm = np.linalg.norm(Ax, ord=np.inf)
    x = Ax / norm
    if np.linalg.norm(Ax - x * norm) < tolerance:
        break
eigenvalue = np.dot(np.dot(A, x).T, x) / np.dot(x.T, x)
print("Dominant Eigenvalue:")
print(eigenvalue[0, 0])
print("\nCorresponding Eigenvector:")
print(x)

Dominant Eigenvalue:
10.047619047619047

Corresponding Eigenvector:
[[0.5 ]
 [1.  ]
 [0.25]]



* ( c ) Utiliza una rutina general de la biblioteca de sistemas de valores propios reales para calcular todos los valores propios y vectores propios de la matriz. vectores propios de la matriz, y compare los resultados con los obtenidos en las partes a y b.

In [20]:

A = np.array([[2, 3, 2],
              [10, 3, 4],
              [3, 6, 1]])
eigenvalues_np, eigenvectors_np = np.linalg.eig(A)
print("Eigenvalues (NumPy):")
print(eigenvalues_np)
print("\nEigenvectors (NumPy):")
print(eigenvectors_np)
print("\nDominant Eigenvalue (Power Iteration):")
print(eigenvalue[0, 0])
print("\nCorresponding Eigenvector (Power Iteration):")
print(x)

Eigenvalues (NumPy):
[11. -2. -3.]

Eigenvectors (NumPy):
[[ 0.37139068  0.18257419  0.        ]
 [ 0.74278135  0.36514837 -0.5547002 ]
 [ 0.55708601 -0.91287093  0.83205029]]

Dominant Eigenvalue (Power Iteration):
10.047619047619047

Corresponding Eigenvector (Power Iteration):
[[0.5 ]
 [1.  ]
 [0.25]]


__4.4 Escriba un programa que implemente la iteración cociente de Rayleigh para calcular un valor propio y el correspondiente vector propio de una matriz. Prueba tu programa con la matriz del ejercicio anterior, utilizando un vector inicial aleatorio.__

In [21]:


def rayleigh_quotient_iteration(A, x0, max_iterations=1000, tolerance=1e-6):
    x = x0 / np.linalg.norm(x0)
    eigenvalue = np.dot(np.dot(x.T, A), x) / np.dot(x.T, x)
    for i in range(max_iterations):
        y = np.linalg.solve(A - eigenvalue * np.eye(A.shape[0]), x)
        y_norm = np.linalg.norm(y)
        x = y / y_norm
        eigenvalue_new = np.dot(np.dot(x.T, A), x) / np.dot(x.T, x)
        if np.abs(eigenvalue_new - eigenvalue) < tolerance:
            break
        eigenvalue = eigenvalue_new
    eigenvector = x
    return eigenvalue, eigenvector
A = np.array([[6, 2, 1],
              [2, 3, 1],
              [1, 1, 1]])
x0 = np.random.rand(A.shape[0])
eigenvalue, eigenvector = rayleigh_quotient_iteration(A, x0)
print("Eigenvalue (Rayleigh Quotient Iteration):")
print(eigenvalue)
print("\nEigenvector (Rayleigh Quotient Iteration):")
print(eigenvector)

Eigenvalue (Rayleigh Quotient Iteration):
7.287991943132486

Eigenvector (Rayleigh Quotient Iteration):
[0.86643225 0.45305757 0.20984279]


__4.6  Implementa la siguiente versión simple de iteración QR con desplazamientos para calcular los valores propios de una matriz real general A.__

Repetir hasta la convergencia : 

1. $\sigma = a_{n,n}$
2. Compute QR factorization $ QR = A - \sigma I$
3. $ A = RQ + \sigma I $

In [22]:


def qr_iteration_with_shift(A, max_iterations=1000, tolerance=1e-6):
    n = A.shape[0]
    eigenvalues = np.zeros(n)

    for i in range(max_iterations):
        # Step 1: Choose the shift (using the corner entry)
        sigma = A[n - 1, n - 1]
        # Step 2: Compute the QR factorization
        Q, R = np.linalg.qr(A - sigma * np.eye(n))

        # Step 3: Update A
        A = np.dot(R, Q) + sigma * np.eye(n)
        off_diag = np.sum(np.abs(A - np.diag(np.diagonal(A))))
        if off_diag < tolerance:
            break
    eigenvalues = np.diagonal(A)
    return eigenvalues
A = np.array([[9, 4.5, 3],
              [-56, -28, -18],
              [60, 30, 19]])
A1 = np.array([[2, 3, 2], [10, 3, 4], [3, 6, 1]])
A2 = np.array([[6, 2, 1], [2, 3, 1], [1, 1, 1]])

eigenvalues = qr_iteration_with_shift(A)
eigenvalues1 = qr_iteration_with_shift(A1)
eigenvalues2 = qr_iteration_with_shift(A2)
print("Eigenvalues:", eigenvalues)
print("Eigenvalues:", eigenvalues1)
print("Eigenvalues:", eigenvalues2)

Eigenvalues: [-1.  0.  1.]
Eigenvalues: [11. -3. -2.]
Eigenvalues: [7.28799214 2.13307448 0.57893339]


__4.14 ( a)  La función exponencial matricial de una matriz  viene definida por la serie infinita infinita__  
$$
\begin{align}
    \exp ( A) = I + A + \frac{A^2}{2!} + \frac{A^3}{3!} \cdots
\end{align}
$$

Escribe un programa para evaluar $ \exp ( A )$ usando la definicíon de la serie anterior. 


In [23]:

def matrix_exp_series(A, tol=1e-10):
   
    n = A.shape[0]
    exp_A = np.eye(n)  
    term = np.eye(n)    
    k = 1               

    while np.linalg.norm(term) > tol:
        term = np.dot(term, A) / k
        exp_A = exp_A + term
        k += 1

    return exp_A



* ( b )  Una forma alternativa de calcular la matriz exponencial utiliza la descomposición valor propio-vector propio
$$
\begin{align}
    A = U diag(\lambda_1 ,\cdots ,\lambda_n)U^{-1}
\end{align}
$$

donde $ \lambda_1, \cdots, \lambda_n $ son los valores propios de  A y U es una matriz cuyas columnas son los vectores propios correspondientes.Entonces la exponencial matricial viene dada por:
$$
\begin{align}
    A = U diag( \exp^{\lambda_1} ,\cdots ,\exp^{\lambda_n})U^{-1}
\end{align}
$$
Escriba un segundo programa para evaluar $ \exp(A) $ usando este método.


In [24]:
def matrix_exp_eigen(A):
    
    eigenvalues, eigenvectors = np.linalg.eig(A)
    exp_eigenvalues = np.exp(eigenvalues)
    U = eigenvectors
    U_inv = np.linalg.inv(U)
    exp_diag = np.diag(exp_eigenvalues)
    exp_A = U @ exp_diag @ U_inv
    return exp_A


Pruebe  ambos metodos usando cada una de las siguientes matrices de prueba:
$$
\begin{align}
    A_1 = \begin{bmatrix}
     2  & -1  \\
     -1 & 2 
    \end{bmatrix} \\
     A_2 = \begin{bmatrix}
     -49 & 24  \\
     -64 & 31 
    \end{bmatrix}
\end{align}
$$


In [25]:
A1 = np.array([[2, -1], [-1, 2]])
A2 = np.array([[-49, 24], [-64, 31]])

Compare sus resultados con los de una función de python para calcular la matriz exponencial. ¿Cuál de tus dos rutinas es más precisa y robusta?

Intenta explicar por qué. Consulte [275] para conocer varios métodos adicionales para calcular la matriz exponencial.

In [26]:

exp_series_A1 = matrix_exp_series(A1)
exp_eigen_A1 = matrix_exp_eigen(A1)

exp_series_A2 = matrix_exp_series(A2)
exp_eigen_A2 = matrix_exp_eigen(A2)

# Print results
print("\nMatriz exponential usando la serie para A1:")
print(exp_series_A1)
print("\nMatriz exponential usando eigenvalue-eigenvector decomposition para A1:")
print(exp_eigen_A1)

print("\nMatriz exponential usando la serie para A2:")
print(exp_series_A2)
print("\nMatriz exponential usando eigenvalue-eigenvector decomposition para A2:")
print(exp_eigen_A2)



Matriz exponential usando la serie para A1:
[[11.40190938 -8.68362755]
 [-8.68362755 11.40190938]]

Matriz exponential usando eigenvalue-eigenvector decomposition para A1:
[[11.40190938 -8.68362755]
 [-8.68362755 11.40190938]]

Matriz exponential usando la serie para A2:
[[-0.73575876  0.5518191 ]
 [-1.4715176   1.10363824]]

Matriz exponential usando eigenvalue-eigenvector decomposition para A2:
[[-0.73575876  0.5518191 ]
 [-1.4715176   1.10363824]]


Si bien ambos programas calculan $exp(A)$ pero lo que se puede observar que se diferencian en los tipos de matrices para los cuales son efectivos. El que utiliza la serie Taylor es más general y puede manejar una variedad más amplia de matrices, mientras que el segundo  es más eficiente para matrices diagonalizables. 


# Conclusión

En conclusión,Los valores propios y los vectores propios nos ayudan a comprender las características de la transformación lineal. se puede utilizar el método de potencia para obtener el valor propio más grande y el vector propio correspondiente de una matriz. El método de la potencia inversa puede ayudarnos a obtener el valor propio más pequeño y el vector propio correspondiente de una matriz. El método de potencia desplazada puede obtener todos los demás valores propios/vectores propios de una matriz. Otro método ampliamente usado para estimar los valores propios es el método QR.